### PR TITLE
Package with a unit conversion function

### PR DESCRIPTION
**Pull request by Starryz**
MVP: package with a unit conversion function

### CODE REVIEW

**Comment by rudeboybert** [comment]
Hey @Starryz, heads up: https://github.com/390-2020-09-Fall/foofactors/pull/2#issuecomment-703735316 about the base branch

**Comment by rudeboybert** [comment]
@Serenali1108 After Starry fixes the base branch, could you review:
1. Run install and check
1. Test the functions/data sets
1. Make sure help files look good

**Comment by Starryz** [comment]
> Hey @Starryz, heads up: [#2 (comment)](https://github.com/390-2020-09-Fall/foofactors/pull/2#issuecomment-703735316) about the base branch

thanks for the reminder! done!

**Comment by Serenali1108** [comment]
I have installed and checked, and they worked good for me now. The functions also look good to me. I think there was some connection problem before at my end.

**Comment by rudeboybert** [comment]
Heads up @Starryz and @Serenali1108, this PR looks good, but I'm going to revert the merge into the `group3` branch for now.

**Pull request merged**
