### PR TITLE
Added roomrank() to rank data frame of dorm rooms

### PR DESCRIPTION
**Pull request by esscott**

### CODE REVIEW

**Comment by sophieml** [comment]
This looks good! The only change I would make would be adding some of your documentation/examples to `README.Rmd`, so package users can preview `room_data` and see how `roomrank()` can be used.

**Comment by esscott** [comment]
> This looks good! The only change I would make would be adding some of your documentation/examples to `README.Rmd`, so package users can preview `room_data` and see how `roomrank()` can be used.

@sophieml All set! Ready for a re-review

**Comment by sophieml** [comment]
looks great! merging into `group2`

**Comment by sophieml** [comment]
oops, re-opening before merging!

**Review by sophieml — APPROVED** [review]

**Comment by rudeboybert** [comment]
This looks good @esscott, and thanks for the review @sophieml. I think I might not have communicated well enough to not do the actual merge into `group2`, but no biggie.

**Comment by rudeboybert** [comment]
Actually, I am going to revert this merge, b/c it's causing merge conflicts for the other group2 participants

**Pull request merged**
